# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build_framwork do
    build_app(
      scheme: "GoogleMapsUtils",
      export_options: {
        method: "app-store",
      },
      output_directory: "./build", 
      archive_path: "./archives",
      include_bitcode: true
    )
  end



  desc "Export xcframework"
  lane :export_xcframework do
  create_xcframework(
    scheme: 'GoogleMapsUtils',
    destinations: ['iOS', 'maccatalyst'],
    xcframework_output_directory: 'Products/xcframeworks'
  )
  end

end
